version: '3.8'

services:
  kratos:
    image: oryd/kratos:v0.11.0
    container_name: kratos
    ports:
      - "4433:4433"
      - "4434:4434"
    command: serve --dev --config /etc/config/kratos/kratos.yml
    volumes:
      - ./config:/etc/config/kratos:ro
      - ./migrations:/etc/migrations:ro
    environment:
      - DSN=postgres://kratos:kratos@db:5432/kratos?sslmode=disable
      - LOG_LEVEL=debug
      - KRATOS_CONFIG_FILE=/etc/config/kratos/kratos.yml
    depends_on:
      - db
      - mailslurper

  db:
    image: postgres:14
    container_name: kratos_db
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: kratos
      POSTGRES_DB: kratos
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  sql-migrate:
    image: postgres:14
    container_name: sql_migrate
    depends_on:
      - db
    entrypoint: >
      bash -c "until pg_isready -h db -p 5432 -U kratos; do sleep 1; done &&
      psql postgres://kratos:kratos@db:5432/kratos -f /migrations/1_init_up.sql"
    volumes:
      - ./migrations:/migrations:ro
    environment:
      - PGPASSWORD=kratos

  kratos-migrate:
    image: oryd/kratos:v0.11.0
    container_name: kratos_migrate
    depends_on:
      - db
      - sql-migrate
    command: migrate sql -e --yes --config /etc/config/kratos/kratos.yml
    volumes:
      - ./config:/etc/config/kratos:ro

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - kratos_net

volumes:
  db_data:

networks:
  kratos_net:
    driver: bridge
