dsn: postgres://kratos:kratos@db:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://localhost:4434/
  admin:
    base_url: http://kratos:4433/

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:3000/
  flows:
    login:
      ui_url: http://localhost:3000/login
    registration:
      enabled: true
      ui_url: http://localhost:3000/register

log:
  level: debug
  format: text

courier:
  smtp:
    connection_uri: smtp://localhost:4436/
